spring:
  datasource:
    url: jdbc:mysql://localhost:3306/byte_tune?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    #  druid
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
  #kafka
  kafka:
    bootstrap-servers: localhost:9092   # Kafka Broker 地址，Producer/Consumer 用来连接 Kafka 的节点
    producer:
      client-id: bytetune-kafka-client  # 生产者客户端 ID，用于标识生产者线程和日志
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息 Key 的序列化方式，通常用 StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 消息 Value 的序列化方式，这里用 JSON 序列化 DTO
    consumer:
      group-id: bytetune-kafka-group    # 消费者组 ID，同组的消费者共享分区消费进度
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 消息 Key 的反序列化方式
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # 消息 Value 的反序列化方式，配合 JsonSerializer 使用
      properties:
        spring.json.trusted.packages: "*"  # 允许反序列化 DTO 的包，* 表示信任所有包

#mybatis-plus
mybatis-plus:
  #  classpath*:mapper/**/*.xml → 扫描 resources/mapper/ 下所有 XML，包括子目录
  mapper-locations: classpath*:mapper/**/*.xml
  #  type-aliases-package → 指定实体类包，这样 XML 中可以直接用类名而不用全限定名
  type-aliases-package: com.bytetune.common.entity
  #   要是其他模块也有entity可以用","分割写多个。
  #    type-aliases-package: com.bytetune.common.entity,com.maizi.bytetune.mongodb,com.maizi.bytetune.file.entity
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# kafka队列名
bytetune:
  kafka:
    topic:
      name: bytetune