<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.maizi</groupId>
        <artifactId>bytetune</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>bytetune-storage-service</artifactId>
    <packaging>jar</packaging><!--基础模块可以用 jar-->
    <name>bytetune-storage（storage 文件存储组件）</name>

    <dependencies>
        <!-- 依赖common模块 -->
        <dependency>
            <groupId>com.maizi</groupId>
            <artifactId>bytetune-common</artifactId>
        </dependency>
        <!-- 依赖contract模块 -->
        <dependency>
            <groupId>com.maizi</groupId>
            <artifactId>bytetune-contract</artifactId>
        </dependency>
        <dependency>
            <groupId>com.maizi</groupId>
            <artifactId>bytetune-messaging</artifactId>
        </dependency>
        <!-- MinIO -->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>
        <dependency>
            <groupId>com.maizi</groupId>
            <artifactId>bytetune-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.maizi</groupId>
            <artifactId>bytetune-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>com.maizi</groupId>
            <artifactId>bytetune-contract</artifactId>
        </dependency>
        <!-- ======================================= -->
        <!-- ======================================= -->
        <!-- Spring Boot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Springdoc OpenAPI -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <!-- 测试 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>