spring.datasource.url=jdbc:mysql://localhost:3306/byte_tune?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=admin123
#????
# WebStatFilter????????Druid Wiki???_??WebStatFilter
#????StatFilter???false
spring.datasource.druid.web-stat-filter.enabled=true
#spring.datasource.druid.web-stat-filter.url-pattern=
#spring.datasource.druid.web-stat-filter.exclusions=
#spring.datasource.druid.web-stat-filter.session-stat-enable=
#spring.datasource.druid.web-stat-filter.session-stat-max-count=
#spring.datasource.druid.web-stat-filter.principal-session-name=
#spring.datasource.druid.web-stat-filter.principal-cookie-name=
#spring.datasource.druid.web-stat-filter.profile-enable=
# StatViewServlet????????Druid Wiki???_StatViewServlet??
#????StatViewServlet??????????false???????????????????????????????????
spring.datasource.druid.stat-view-servlet.enabled=true
#spring.datasource.druid.stat-view-servlet.url-pattern=
#spring.datasource.druid.stat-view-servlet.reset-enable=
#spring.datasource.druid.stat-view-servlet.login-username=
#spring.datasource.druid.stat-view-servlet.login-password=
#spring.datasource.druid.stat-view-servlet.allow=
#spring.datasource.druid.stat-view-servlet.deny=
## Spring??????????Druid Github Wiki???_Druid?Spring??????
#spring.datasource.druid.aop-patterns=\
# Spring??AOP?????x.y.z.service.*,??????????